server:
  context-path: /rs
  port: 8800

logging:
  level:
    org.springframework.security: DEBUG

security:
  user:
    password: 123456
  oauth2:
   resource:
     userInfoUri: http://localhost:9800/auth/me
     preferTokenInfo: false