server:
  context-path: /auth
  port: 9800
logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    password: none



jwt:
  keystore:
    file: jwt.jks
    password: mySecretKey
    alias: jwt-default-test